# Nichi Project Configuration
spring:
  application:
    name: Nichi

  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/nichi_db
    username: root
    password: ${MYSQL_PASSWORD:253647} # ????????????
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA / Hibernate ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # Redis ?? (????????????)
  data:
    redis:
      host: localhost
      port: 6379
      database: 0 # ???? 0 ??????? Key ??????
      lettuce:
        pool:
          max-active: 8
          max-idle: 8

# ?????
server:
  port: 8080

# ????
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

# Swagger3 / SpringDoc ??
springdoc:
  packages-to-scan: top.sakablog.nichi.controller
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    enabled: true

# Sa-Token ?? (????)
sa-token:
  token-name: satoken          # token ?? (?? Cookie/Header ?)
  timeout: 2592000             # token ??????? (?? 30 ?)
  active-timeout: -1           # token ????? (???????????)?-1 ?????
  is-concurrent: true          # ??????????????
  is-share: false              # ????????????????? token
  token-style: uuid            # token ??
  is-log: true                 # ????????

sms4j:
  mail:
    enabled: true
    config-id: default
    smtp-server: ${MAIL_SMTP_SERVER:smtp.qq.com}
    port: ${MAIL_PORT:465}
    from-address: ${MAIL_FROM_ADDRESS:nichigo_client@qq.com}
    username: ${MAIL_USERNAME:nichigo_client@qq.com}
    password: ${MAIL_PASSWORD:fryzhmxwgylzcjcc}
    nick-name: NichiGo
    ssl: true
    auth: true
    retry-interval: 5
    max-retries: 1
    verify-code-subject: Nichi 验证码
